/*
 * This file is generated by jOOQ.
 */
package jooq.auth.tables.records;


import jooq.auth.tables.Role;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RoleRecord extends UpdatableRecordImpl<RoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>auth.role.id</code>.
     */
    public RoleRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>auth.role.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>auth.role.sys_name</code>.
     */
    public RoleRecord setSysName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>auth.role.sys_name</code>.
     */
    public String getSysName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>auth.role.description</code>.
     */
    public RoleRecord setDescription(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>auth.role.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>auth.role.is_actual</code>.
     */
    public RoleRecord setIsActual(Boolean value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>auth.role.is_actual</code>.
     */
    public Boolean getIsActual() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoleRecord
     */
    public RoleRecord() {
        super(Role.ROLE);
    }

    /**
     * Create a detached, initialised RoleRecord
     */
    public RoleRecord(Long id, String sysName, String description, Boolean isActual) {
        super(Role.ROLE);

        setId(id);
        setSysName(sysName);
        setDescription(description);
        setIsActual(isActual);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised RoleRecord
     */
    public RoleRecord(jooq.auth.tables.pojos.Role value) {
        super(Role.ROLE);

        if (value != null) {
            setId(value.getId());
            setSysName(value.getSysName());
            setDescription(value.getDescription());
            setIsActual(value.getIsActual());
            resetTouchedOnNotNull();
        }
    }
}
