/*
 * This file is generated by jOOQ.
 */
package jooq.auth.tables.records;


import java.time.LocalDate;

import jooq.auth.tables.UserData;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserDataRecord extends UpdatableRecordImpl<UserDataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>auth.user_data.id</code>.
     */
    public UserDataRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>auth.user_data.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>auth.user_data.user_id</code>.
     */
    public UserDataRecord setUserId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>auth.user_data.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>auth.user_data.full_name</code>.
     */
    public UserDataRecord setFullName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>auth.user_data.full_name</code>.
     */
    public String getFullName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>auth.user_data.birth_date</code>.
     */
    public UserDataRecord setBirthDate(LocalDate value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>auth.user_data.birth_date</code>.
     */
    public LocalDate getBirthDate() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>auth.user_data.country</code>.
     */
    public UserDataRecord setCountry(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>auth.user_data.country</code>.
     */
    public String getCountry() {
        return (String) get(4);
    }

    /**
     * Setter for <code>auth.user_data.number_phone</code>.
     */
    public UserDataRecord setNumberPhone(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>auth.user_data.number_phone</code>.
     */
    public String getNumberPhone() {
        return (String) get(5);
    }

    /**
     * Setter for <code>auth.user_data.passport_series</code>.
     */
    public UserDataRecord setPassportSeries(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>auth.user_data.passport_series</code>.
     */
    public String getPassportSeries() {
        return (String) get(6);
    }

    /**
     * Setter for <code>auth.user_data.passport_number</code>.
     */
    public UserDataRecord setPassportNumber(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>auth.user_data.passport_number</code>.
     */
    public String getPassportNumber() {
        return (String) get(7);
    }

    /**
     * Setter for <code>auth.user_data.passport_issued_by</code>.
     */
    public UserDataRecord setPassportIssuedBy(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>auth.user_data.passport_issued_by</code>.
     */
    public String getPassportIssuedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>auth.user_data.passport_issue_date</code>.
     */
    public UserDataRecord setPassportIssueDate(LocalDate value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>auth.user_data.passport_issue_date</code>.
     */
    public LocalDate getPassportIssueDate() {
        return (LocalDate) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserDataRecord
     */
    public UserDataRecord() {
        super(UserData.USER_DATA);
    }

    /**
     * Create a detached, initialised UserDataRecord
     */
    public UserDataRecord(Long id, Long userId, String fullName, LocalDate birthDate, String country, String numberPhone, String passportSeries, String passportNumber, String passportIssuedBy, LocalDate passportIssueDate) {
        super(UserData.USER_DATA);

        setId(id);
        setUserId(userId);
        setFullName(fullName);
        setBirthDate(birthDate);
        setCountry(country);
        setNumberPhone(numberPhone);
        setPassportSeries(passportSeries);
        setPassportNumber(passportNumber);
        setPassportIssuedBy(passportIssuedBy);
        setPassportIssueDate(passportIssueDate);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised UserDataRecord
     */
    public UserDataRecord(jooq.auth.tables.pojos.UserData value) {
        super(UserData.USER_DATA);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            setFullName(value.getFullName());
            setBirthDate(value.getBirthDate());
            setCountry(value.getCountry());
            setNumberPhone(value.getNumberPhone());
            setPassportSeries(value.getPassportSeries());
            setPassportNumber(value.getPassportNumber());
            setPassportIssuedBy(value.getPassportIssuedBy());
            setPassportIssueDate(value.getPassportIssueDate());
            resetTouchedOnNotNull();
        }
    }
}
