/*
 * This file is generated by jOOQ.
 */
package jooq.auth.tables.records;


import jooq.auth.tables.UserAccount;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserAccountRecord extends UpdatableRecordImpl<UserAccountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>auth.user_account.id</code>.
     */
    public UserAccountRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>auth.user_account.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>auth.user_account.username</code>.
     */
    public UserAccountRecord setUsername(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>auth.user_account.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>auth.user_account.full_name</code>.
     */
    public UserAccountRecord setFullName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>auth.user_account.full_name</code>.
     */
    public String getFullName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>auth.user_account.enabled</code>.
     */
    public UserAccountRecord setEnabled(Boolean value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>auth.user_account.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>auth.user_account.password</code>.
     */
    public UserAccountRecord setPassword(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>auth.user_account.password</code>.
     */
    public String getPassword() {
        return (String) get(4);
    }

    /**
     * Setter for <code>auth.user_account.number_phone</code>.
     */
    public UserAccountRecord setNumberPhone(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>auth.user_account.number_phone</code>.
     */
    public String getNumberPhone() {
        return (String) get(5);
    }

    /**
     * Setter for <code>auth.user_account.role_id</code>.
     */
    public UserAccountRecord setRoleId(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>auth.user_account.role_id</code>.
     */
    public Long getRoleId() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserAccountRecord
     */
    public UserAccountRecord() {
        super(UserAccount.USER_ACCOUNT);
    }

    /**
     * Create a detached, initialised UserAccountRecord
     */
    public UserAccountRecord(Long id, String username, String fullName, Boolean enabled, String password, String numberPhone, Long roleId) {
        super(UserAccount.USER_ACCOUNT);

        setId(id);
        setUsername(username);
        setFullName(fullName);
        setEnabled(enabled);
        setPassword(password);
        setNumberPhone(numberPhone);
        setRoleId(roleId);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised UserAccountRecord
     */
    public UserAccountRecord(jooq.auth.tables.pojos.UserAccount value) {
        super(UserAccount.USER_ACCOUNT);

        if (value != null) {
            setId(value.getId());
            setUsername(value.getUsername());
            setFullName(value.getFullName());
            setEnabled(value.getEnabled());
            setPassword(value.getPassword());
            setNumberPhone(value.getNumberPhone());
            setRoleId(value.getRoleId());
            resetTouchedOnNotNull();
        }
    }
}
