/*
 * This file is generated by jOOQ.
 */
package jooq.auth;


import java.util.Arrays;
import java.util.List;

import jooq.DefaultCatalog;
import jooq.auth.tables.Role;
import jooq.auth.tables.UserAccount;
import jooq.auth.tables.UserData;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Auth extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>auth</code>
     */
    public static final Auth AUTH = new Auth();

    /**
     * The table <code>auth.role</code>.
     */
    public final Role ROLE = Role.ROLE;

    /**
     * The table <code>auth.user_account</code>.
     */
    public final UserAccount USER_ACCOUNT = UserAccount.USER_ACCOUNT;

    /**
     * The table <code>auth.user_data</code>.
     */
    public final UserData USER_DATA = UserData.USER_DATA;

    /**
     * No further instances allowed
     */
    private Auth() {
        super(DSL.name("auth"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Role.ROLE,
            UserAccount.USER_ACCOUNT,
            UserData.USER_DATA
        );
    }
}
