/*
 * This file is generated by jOOQ.
 */
package jooq.auth;


import jooq.auth.tables.Role;
import jooq.auth.tables.UserAccount;
import jooq.auth.tables.UserData;
import jooq.auth.tables.records.RoleRecord;
import jooq.auth.tables.records.UserAccountRecord;
import jooq.auth.tables.records.UserDataRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * auth.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<RoleRecord> ROLE_PK = Internal.createUniqueKey(Role.ROLE, DSL.name("role_pk"), new TableField[] { Role.ROLE.ID }, true);
    public static final UniqueKey<RoleRecord> ROLE_UK1 = Internal.createUniqueKey(Role.ROLE, DSL.name("role_uk1"), new TableField[] { Role.ROLE.SYS_NAME }, true);
    public static final UniqueKey<UserAccountRecord> USER_ACCOUNT_PK = Internal.createUniqueKey(UserAccount.USER_ACCOUNT, DSL.name("user_account_pk"), new TableField[] { UserAccount.USER_ACCOUNT.ID }, true);
    public static final UniqueKey<UserAccountRecord> USER_ACCOUNT_UK1 = Internal.createUniqueKey(UserAccount.USER_ACCOUNT, DSL.name("user_account_uk1"), new TableField[] { UserAccount.USER_ACCOUNT.USERNAME }, true);
    public static final UniqueKey<UserDataRecord> USER_DATA_PK = Internal.createUniqueKey(UserData.USER_DATA, DSL.name("user_data_pk"), new TableField[] { UserData.USER_DATA.ID }, true);
    public static final UniqueKey<UserDataRecord> USER_DATA_UK1 = Internal.createUniqueKey(UserData.USER_DATA, DSL.name("user_data_uk1"), new TableField[] { UserData.USER_DATA.USER_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<UserAccountRecord, RoleRecord> USER_ACCOUNT__ROLE_FK1 = Internal.createForeignKey(UserAccount.USER_ACCOUNT, DSL.name("role_fk1"), new TableField[] { UserAccount.USER_ACCOUNT.ROLE_ID }, Keys.ROLE_PK, new TableField[] { Role.ROLE.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<UserDataRecord, UserAccountRecord> USER_DATA__USER_ACCOUNT_FK1 = Internal.createForeignKey(UserData.USER_DATA, DSL.name("user_account_fk1"), new TableField[] { UserData.USER_DATA.USER_ID }, Keys.USER_ACCOUNT_PK, new TableField[] { UserAccount.USER_ACCOUNT.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);
}
