/*
 * This file is generated by jOOQ.
 */
package jooq.auth;


import jooq.auth.tables.Role;
import jooq.auth.tables.UserAccount;
import jooq.auth.tables.UserData;


/**
 * Convenience access to all tables in auth.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>auth.role</code>.
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>auth.user_account</code>.
     */
    public static final UserAccount USER_ACCOUNT = UserAccount.USER_ACCOUNT;

    /**
     * The table <code>auth.user_data</code>.
     */
    public static final UserData USER_DATA = UserData.USER_DATA;
}
