/*
 * This file is generated by jOOQ.
 */
package jooq.auth.tables;


import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import jooq.auth.Auth;
import jooq.auth.Keys;
import jooq.auth.tables.UserAccount.UserAccountPath;
import jooq.auth.tables.records.UserDataRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserData extends TableImpl<UserDataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>auth.user_data</code>
     */
    public static final UserData USER_DATA = new UserData();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserDataRecord> getRecordType() {
        return UserDataRecord.class;
    }

    /**
     * The column <code>auth.user_data.id</code>.
     */
    public final TableField<UserDataRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>auth.user_data.user_id</code>.
     */
    public final TableField<UserDataRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>auth.user_data.full_name</code>.
     */
    public final TableField<UserDataRecord, String> FULL_NAME = createField(DSL.name("full_name"), SQLDataType.VARCHAR(4000).nullable(false), this, "");

    /**
     * The column <code>auth.user_data.birth_date</code>.
     */
    public final TableField<UserDataRecord, LocalDate> BIRTH_DATE = createField(DSL.name("birth_date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>auth.user_data.country</code>.
     */
    public final TableField<UserDataRecord, String> COUNTRY = createField(DSL.name("country"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>auth.user_data.number_phone</code>.
     */
    public final TableField<UserDataRecord, String> NUMBER_PHONE = createField(DSL.name("number_phone"), SQLDataType.VARCHAR(500).nullable(false), this, "");

    /**
     * The column <code>auth.user_data.passport_series</code>.
     */
    public final TableField<UserDataRecord, String> PASSPORT_SERIES = createField(DSL.name("passport_series"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>auth.user_data.passport_number</code>.
     */
    public final TableField<UserDataRecord, String> PASSPORT_NUMBER = createField(DSL.name("passport_number"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>auth.user_data.passport_issued_by</code>.
     */
    public final TableField<UserDataRecord, String> PASSPORT_ISSUED_BY = createField(DSL.name("passport_issued_by"), SQLDataType.VARCHAR(150).nullable(false), this, "");

    /**
     * The column <code>auth.user_data.passport_issue_date</code>.
     */
    public final TableField<UserDataRecord, LocalDate> PASSPORT_ISSUE_DATE = createField(DSL.name("passport_issue_date"), SQLDataType.LOCALDATE.nullable(false), this, "");

    private UserData(Name alias, Table<UserDataRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserData(Name alias, Table<UserDataRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>auth.user_data</code> table reference
     */
    public UserData(String alias) {
        this(DSL.name(alias), USER_DATA);
    }

    /**
     * Create an aliased <code>auth.user_data</code> table reference
     */
    public UserData(Name alias) {
        this(alias, USER_DATA);
    }

    /**
     * Create a <code>auth.user_data</code> table reference
     */
    public UserData() {
        this(DSL.name("user_data"), null);
    }

    public <O extends Record> UserData(Table<O> path, ForeignKey<O, UserDataRecord> childPath, InverseForeignKey<O, UserDataRecord> parentPath) {
        super(path, childPath, parentPath, USER_DATA);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UserDataPath extends UserData implements Path<UserDataRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UserDataPath(Table<O> path, ForeignKey<O, UserDataRecord> childPath, InverseForeignKey<O, UserDataRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private UserDataPath(Name alias, Table<UserDataRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public UserDataPath as(String alias) {
            return new UserDataPath(DSL.name(alias), this);
        }

        @Override
        public UserDataPath as(Name alias) {
            return new UserDataPath(alias, this);
        }

        @Override
        public UserDataPath as(Table<?> alias) {
            return new UserDataPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Auth.AUTH;
    }

    @Override
    public Identity<UserDataRecord, Long> getIdentity() {
        return (Identity<UserDataRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<UserDataRecord> getPrimaryKey() {
        return Keys.USER_DATA_PK;
    }

    @Override
    public List<UniqueKey<UserDataRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.USER_DATA_UK1);
    }

    @Override
    public List<ForeignKey<UserDataRecord, ?>> getReferences() {
        return Arrays.asList(Keys.USER_DATA__USER_ACCOUNT_FK1);
    }

    private transient UserAccountPath _userAccount;

    /**
     * Get the implicit join path to the <code>auth.user_account</code> table.
     */
    public UserAccountPath userAccount() {
        if (_userAccount == null)
            _userAccount = new UserAccountPath(this, Keys.USER_DATA__USER_ACCOUNT_FK1, null);

        return _userAccount;
    }

    @Override
    public UserData as(String alias) {
        return new UserData(DSL.name(alias), this);
    }

    @Override
    public UserData as(Name alias) {
        return new UserData(alias, this);
    }

    @Override
    public UserData as(Table<?> alias) {
        return new UserData(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserData rename(String name) {
        return new UserData(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserData rename(Name name) {
        return new UserData(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserData rename(Table<?> name) {
        return new UserData(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserData where(Condition condition) {
        return new UserData(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserData where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserData where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserData where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserData where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserData where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserData where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserData where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserData whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserData whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
