/*
 * This file is generated by jOOQ.
 */
package jooq.money_transfer.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import jooq.money_transfer.Keys;
import jooq.money_transfer.MoneyTransfer;
import jooq.money_transfer.tables.Account.AccountPath;
import jooq.money_transfer.tables.records.AccountStatusRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccountStatus extends TableImpl<AccountStatusRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>money_transfer.account_status</code>
     */
    public static final AccountStatus ACCOUNT_STATUS = new AccountStatus();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AccountStatusRecord> getRecordType() {
        return AccountStatusRecord.class;
    }

    /**
     * The column <code>money_transfer.account_status.id</code>.
     */
    public final TableField<AccountStatusRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>money_transfer.account_status.status_code</code>.
     */
    public final TableField<AccountStatusRecord, String> STATUS_CODE = createField(DSL.name("status_code"), SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>money_transfer.account_status.description</code>.
     */
    public final TableField<AccountStatusRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>money_transfer.account_status.name</code>.
     */
    public final TableField<AccountStatusRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100), this, "");

    private AccountStatus(Name alias, Table<AccountStatusRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AccountStatus(Name alias, Table<AccountStatusRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>money_transfer.account_status</code> table
     * reference
     */
    public AccountStatus(String alias) {
        this(DSL.name(alias), ACCOUNT_STATUS);
    }

    /**
     * Create an aliased <code>money_transfer.account_status</code> table
     * reference
     */
    public AccountStatus(Name alias) {
        this(alias, ACCOUNT_STATUS);
    }

    /**
     * Create a <code>money_transfer.account_status</code> table reference
     */
    public AccountStatus() {
        this(DSL.name("account_status"), null);
    }

    public <O extends Record> AccountStatus(Table<O> path, ForeignKey<O, AccountStatusRecord> childPath, InverseForeignKey<O, AccountStatusRecord> parentPath) {
        super(path, childPath, parentPath, ACCOUNT_STATUS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AccountStatusPath extends AccountStatus implements Path<AccountStatusRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AccountStatusPath(Table<O> path, ForeignKey<O, AccountStatusRecord> childPath, InverseForeignKey<O, AccountStatusRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AccountStatusPath(Name alias, Table<AccountStatusRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AccountStatusPath as(String alias) {
            return new AccountStatusPath(DSL.name(alias), this);
        }

        @Override
        public AccountStatusPath as(Name alias) {
            return new AccountStatusPath(alias, this);
        }

        @Override
        public AccountStatusPath as(Table<?> alias) {
            return new AccountStatusPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : MoneyTransfer.MONEY_TRANSFER;
    }

    @Override
    public Identity<AccountStatusRecord, Long> getIdentity() {
        return (Identity<AccountStatusRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AccountStatusRecord> getPrimaryKey() {
        return Keys.ACCOUNT_STATUS_PKEY;
    }

    @Override
    public List<UniqueKey<AccountStatusRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.ACCOUNT_STATUS_STATUS_CODE_KEY);
    }

    private transient AccountPath _account;

    /**
     * Get the implicit to-many join path to the
     * <code>money_transfer.account</code> table
     */
    public AccountPath account() {
        if (_account == null)
            _account = new AccountPath(this, null, Keys.ACCOUNT__ACCOUNT_STATUS_FK.getInverseKey());

        return _account;
    }

    @Override
    public AccountStatus as(String alias) {
        return new AccountStatus(DSL.name(alias), this);
    }

    @Override
    public AccountStatus as(Name alias) {
        return new AccountStatus(alias, this);
    }

    @Override
    public AccountStatus as(Table<?> alias) {
        return new AccountStatus(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountStatus rename(String name) {
        return new AccountStatus(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountStatus rename(Name name) {
        return new AccountStatus(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountStatus rename(Table<?> name) {
        return new AccountStatus(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountStatus where(Condition condition) {
        return new AccountStatus(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountStatus where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountStatus where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountStatus where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccountStatus where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccountStatus where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccountStatus where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccountStatus where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountStatus whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountStatus whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
