/*
 * This file is generated by jOOQ.
 */
package jooq.money_transfer.tables;


import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import jooq.auth.tables.UserAccount.UserAccountPath;
import jooq.money_transfer.Keys;
import jooq.money_transfer.MoneyTransfer;
import jooq.money_transfer.tables.CurrencyType.CurrencyTypePath;
import jooq.money_transfer.tables.TransactionHistory.TransactionHistoryPath;
import jooq.money_transfer.tables.records.AccountRecord;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Account extends TableImpl<AccountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>money_transfer.account</code>
     */
    public static final Account ACCOUNT = new Account();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AccountRecord> getRecordType() {
        return AccountRecord.class;
    }

    /**
     * The column <code>money_transfer.account.id</code>.
     */
    public final TableField<AccountRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>money_transfer.account.user_account_id</code>.
     */
    public final TableField<AccountRecord, Long> USER_ACCOUNT_ID = createField(DSL.name("user_account_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>money_transfer.account.account_number</code>.
     */
    public final TableField<AccountRecord, String> ACCOUNT_NUMBER = createField(DSL.name("account_number"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>money_transfer.account.balance</code>.
     */
    public final TableField<AccountRecord, BigDecimal> BALANCE = createField(DSL.name("balance"), SQLDataType.NUMERIC(14, 2).nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.NUMERIC)), this, "");

    /**
     * The column <code>money_transfer.account.created_at</code>.
     */
    public final TableField<AccountRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>money_transfer.account.currency</code>.
     */
    public final TableField<AccountRecord, Long> CURRENCY = createField(DSL.name("currency"), SQLDataType.BIGINT.nullable(false), this, "");

    private Account(Name alias, Table<AccountRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Account(Name alias, Table<AccountRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>money_transfer.account</code> table reference
     */
    public Account(String alias) {
        this(DSL.name(alias), ACCOUNT);
    }

    /**
     * Create an aliased <code>money_transfer.account</code> table reference
     */
    public Account(Name alias) {
        this(alias, ACCOUNT);
    }

    /**
     * Create a <code>money_transfer.account</code> table reference
     */
    public Account() {
        this(DSL.name("account"), null);
    }

    public <O extends Record> Account(Table<O> path, ForeignKey<O, AccountRecord> childPath, InverseForeignKey<O, AccountRecord> parentPath) {
        super(path, childPath, parentPath, ACCOUNT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AccountPath extends Account implements Path<AccountRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AccountPath(Table<O> path, ForeignKey<O, AccountRecord> childPath, InverseForeignKey<O, AccountRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AccountPath(Name alias, Table<AccountRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AccountPath as(String alias) {
            return new AccountPath(DSL.name(alias), this);
        }

        @Override
        public AccountPath as(Name alias) {
            return new AccountPath(alias, this);
        }

        @Override
        public AccountPath as(Table<?> alias) {
            return new AccountPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : MoneyTransfer.MONEY_TRANSFER;
    }

    @Override
    public Identity<AccountRecord, Long> getIdentity() {
        return (Identity<AccountRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AccountRecord> getPrimaryKey() {
        return Keys.ACCOUNT_PK;
    }

    @Override
    public List<UniqueKey<AccountRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.ACCOUNT_ACCOUNT_NUMBER_KEY);
    }

    @Override
    public List<ForeignKey<AccountRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ACCOUNT__CURRENCY_TYPE_FK, Keys.ACCOUNT__USER_ACCOUNT_FK1);
    }

    private transient CurrencyTypePath _currencyType;

    /**
     * Get the implicit join path to the
     * <code>money_transfer.currency_type</code> table.
     */
    public CurrencyTypePath currencyType() {
        if (_currencyType == null)
            _currencyType = new CurrencyTypePath(this, Keys.ACCOUNT__CURRENCY_TYPE_FK, null);

        return _currencyType;
    }

    private transient UserAccountPath _userAccount;

    /**
     * Get the implicit join path to the <code>auth.user_account</code> table.
     */
    public UserAccountPath userAccount() {
        if (_userAccount == null)
            _userAccount = new UserAccountPath(this, Keys.ACCOUNT__USER_ACCOUNT_FK1, null);

        return _userAccount;
    }

    private transient TransactionHistoryPath _fromAccountFk;

    /**
     * Get the implicit to-many join path to the
     * <code>money_transfer.transaction_history</code> table, via the
     * <code>from_account_fk</code> key
     */
    public TransactionHistoryPath fromAccountFk() {
        if (_fromAccountFk == null)
            _fromAccountFk = new TransactionHistoryPath(this, null, Keys.TRANSACTION_HISTORY__FROM_ACCOUNT_FK.getInverseKey());

        return _fromAccountFk;
    }

    private transient TransactionHistoryPath _toAccountFk;

    /**
     * Get the implicit to-many join path to the
     * <code>money_transfer.transaction_history</code> table, via the
     * <code>to_account_fk</code> key
     */
    public TransactionHistoryPath toAccountFk() {
        if (_toAccountFk == null)
            _toAccountFk = new TransactionHistoryPath(this, null, Keys.TRANSACTION_HISTORY__TO_ACCOUNT_FK.getInverseKey());

        return _toAccountFk;
    }

    @Override
    public List<Check<AccountRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("account_balance_check"), "((balance >= (0)::numeric))", true)
        );
    }

    @Override
    public Account as(String alias) {
        return new Account(DSL.name(alias), this);
    }

    @Override
    public Account as(Name alias) {
        return new Account(alias, this);
    }

    @Override
    public Account as(Table<?> alias) {
        return new Account(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Account rename(String name) {
        return new Account(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Account rename(Name name) {
        return new Account(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Account rename(Table<?> name) {
        return new Account(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Account where(Condition condition) {
        return new Account(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Account where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Account where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Account where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Account where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Account where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Account where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Account where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Account whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Account whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
