/*
 * This file is generated by jOOQ.
 */
package jooq.money_transfer.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import jooq.money_transfer.Keys;
import jooq.money_transfer.MoneyTransfer;
import jooq.money_transfer.tables.Account.AccountPath;
import jooq.money_transfer.tables.records.AccountTypeRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccountType extends TableImpl<AccountTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>money_transfer.account_type</code>
     */
    public static final AccountType ACCOUNT_TYPE = new AccountType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AccountTypeRecord> getRecordType() {
        return AccountTypeRecord.class;
    }

    /**
     * The column <code>money_transfer.account_type.id</code>.
     */
    public final TableField<AccountTypeRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>money_transfer.account_type.type_code</code>.
     */
    public final TableField<AccountTypeRecord, String> TYPE_CODE = createField(DSL.name("type_code"), SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>money_transfer.account_type.description</code>.
     */
    public final TableField<AccountTypeRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>money_transfer.account_type.name</code>.
     */
    public final TableField<AccountTypeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100), this, "");

    private AccountType(Name alias, Table<AccountTypeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AccountType(Name alias, Table<AccountTypeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>money_transfer.account_type</code> table
     * reference
     */
    public AccountType(String alias) {
        this(DSL.name(alias), ACCOUNT_TYPE);
    }

    /**
     * Create an aliased <code>money_transfer.account_type</code> table
     * reference
     */
    public AccountType(Name alias) {
        this(alias, ACCOUNT_TYPE);
    }

    /**
     * Create a <code>money_transfer.account_type</code> table reference
     */
    public AccountType() {
        this(DSL.name("account_type"), null);
    }

    public <O extends Record> AccountType(Table<O> path, ForeignKey<O, AccountTypeRecord> childPath, InverseForeignKey<O, AccountTypeRecord> parentPath) {
        super(path, childPath, parentPath, ACCOUNT_TYPE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AccountTypePath extends AccountType implements Path<AccountTypeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AccountTypePath(Table<O> path, ForeignKey<O, AccountTypeRecord> childPath, InverseForeignKey<O, AccountTypeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AccountTypePath(Name alias, Table<AccountTypeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AccountTypePath as(String alias) {
            return new AccountTypePath(DSL.name(alias), this);
        }

        @Override
        public AccountTypePath as(Name alias) {
            return new AccountTypePath(alias, this);
        }

        @Override
        public AccountTypePath as(Table<?> alias) {
            return new AccountTypePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : MoneyTransfer.MONEY_TRANSFER;
    }

    @Override
    public Identity<AccountTypeRecord, Long> getIdentity() {
        return (Identity<AccountTypeRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AccountTypeRecord> getPrimaryKey() {
        return Keys.ACCOUNT_TYPE_PKEY;
    }

    @Override
    public List<UniqueKey<AccountTypeRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.ACCOUNT_TYPE_TYPE_CODE_KEY);
    }

    private transient AccountPath _account;

    /**
     * Get the implicit to-many join path to the
     * <code>money_transfer.account</code> table
     */
    public AccountPath account() {
        if (_account == null)
            _account = new AccountPath(this, null, Keys.ACCOUNT__ACCOUNT_TYPE_FK.getInverseKey());

        return _account;
    }

    @Override
    public AccountType as(String alias) {
        return new AccountType(DSL.name(alias), this);
    }

    @Override
    public AccountType as(Name alias) {
        return new AccountType(alias, this);
    }

    @Override
    public AccountType as(Table<?> alias) {
        return new AccountType(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountType rename(String name) {
        return new AccountType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountType rename(Name name) {
        return new AccountType(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountType rename(Table<?> name) {
        return new AccountType(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountType where(Condition condition) {
        return new AccountType(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountType where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountType where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountType where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccountType where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccountType where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccountType where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccountType where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountType whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountType whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
