/*
 * This file is generated by jOOQ.
 */
package jooq.money_transfer.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import jooq.money_transfer.Keys;
import jooq.money_transfer.MoneyTransfer;
import jooq.money_transfer.tables.Account.AccountPath;
import jooq.money_transfer.tables.TransactionHistory.TransactionHistoryPath;
import jooq.money_transfer.tables.records.CurrencyTypeRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CurrencyType extends TableImpl<CurrencyTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>money_transfer.currency_type</code>
     */
    public static final CurrencyType CURRENCY_TYPE = new CurrencyType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CurrencyTypeRecord> getRecordType() {
        return CurrencyTypeRecord.class;
    }

    /**
     * The column <code>money_transfer.currency_type.id</code>.
     */
    public final TableField<CurrencyTypeRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>money_transfer.currency_type.currency_code</code>.
     */
    public final TableField<CurrencyTypeRecord, String> CURRENCY_CODE = createField(DSL.name("currency_code"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>money_transfer.currency_type.description</code>.
     */
    public final TableField<CurrencyTypeRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>money_transfer.currency_type.name</code>.
     */
    public final TableField<CurrencyTypeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(20), this, "");

    private CurrencyType(Name alias, Table<CurrencyTypeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CurrencyType(Name alias, Table<CurrencyTypeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>money_transfer.currency_type</code> table
     * reference
     */
    public CurrencyType(String alias) {
        this(DSL.name(alias), CURRENCY_TYPE);
    }

    /**
     * Create an aliased <code>money_transfer.currency_type</code> table
     * reference
     */
    public CurrencyType(Name alias) {
        this(alias, CURRENCY_TYPE);
    }

    /**
     * Create a <code>money_transfer.currency_type</code> table reference
     */
    public CurrencyType() {
        this(DSL.name("currency_type"), null);
    }

    public <O extends Record> CurrencyType(Table<O> path, ForeignKey<O, CurrencyTypeRecord> childPath, InverseForeignKey<O, CurrencyTypeRecord> parentPath) {
        super(path, childPath, parentPath, CURRENCY_TYPE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CurrencyTypePath extends CurrencyType implements Path<CurrencyTypeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CurrencyTypePath(Table<O> path, ForeignKey<O, CurrencyTypeRecord> childPath, InverseForeignKey<O, CurrencyTypeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CurrencyTypePath(Name alias, Table<CurrencyTypeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CurrencyTypePath as(String alias) {
            return new CurrencyTypePath(DSL.name(alias), this);
        }

        @Override
        public CurrencyTypePath as(Name alias) {
            return new CurrencyTypePath(alias, this);
        }

        @Override
        public CurrencyTypePath as(Table<?> alias) {
            return new CurrencyTypePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : MoneyTransfer.MONEY_TRANSFER;
    }

    @Override
    public Identity<CurrencyTypeRecord, Long> getIdentity() {
        return (Identity<CurrencyTypeRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<CurrencyTypeRecord> getPrimaryKey() {
        return Keys.CURRENCY_TYPE_PKEY;
    }

    @Override
    public List<UniqueKey<CurrencyTypeRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CURRENCY_TYPE_CODE_KEY);
    }

    private transient AccountPath _account;

    /**
     * Get the implicit to-many join path to the
     * <code>money_transfer.account</code> table
     */
    public AccountPath account() {
        if (_account == null)
            _account = new AccountPath(this, null, Keys.ACCOUNT__CURRENCY_TYPE_FK.getInverseKey());

        return _account;
    }

    private transient TransactionHistoryPath _transactionHistory;

    /**
     * Get the implicit to-many join path to the
     * <code>money_transfer.transaction_history</code> table
     */
    public TransactionHistoryPath transactionHistory() {
        if (_transactionHistory == null)
            _transactionHistory = new TransactionHistoryPath(this, null, Keys.TRANSACTION_HISTORY__CURRENCY_TYPE_FK.getInverseKey());

        return _transactionHistory;
    }

    @Override
    public CurrencyType as(String alias) {
        return new CurrencyType(DSL.name(alias), this);
    }

    @Override
    public CurrencyType as(Name alias) {
        return new CurrencyType(alias, this);
    }

    @Override
    public CurrencyType as(Table<?> alias) {
        return new CurrencyType(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CurrencyType rename(String name) {
        return new CurrencyType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CurrencyType rename(Name name) {
        return new CurrencyType(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CurrencyType rename(Table<?> name) {
        return new CurrencyType(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CurrencyType where(Condition condition) {
        return new CurrencyType(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CurrencyType where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CurrencyType where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CurrencyType where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CurrencyType where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CurrencyType where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CurrencyType where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CurrencyType where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CurrencyType whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CurrencyType whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
