/*
 * This file is generated by jOOQ.
 */
package jooq.money_transfer.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import jooq.money_transfer.Keys;
import jooq.money_transfer.MoneyTransfer;
import jooq.money_transfer.tables.TransactionHistory.TransactionHistoryPath;
import jooq.money_transfer.tables.records.TransactionTypeRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TransactionType extends TableImpl<TransactionTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>money_transfer.transaction_type</code>
     */
    public static final TransactionType TRANSACTION_TYPE = new TransactionType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TransactionTypeRecord> getRecordType() {
        return TransactionTypeRecord.class;
    }

    /**
     * The column <code>money_transfer.transaction_type.id</code>.
     */
    public final TableField<TransactionTypeRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>money_transfer.transaction_type.type_code</code>.
     */
    public final TableField<TransactionTypeRecord, String> TYPE_CODE = createField(DSL.name("type_code"), SQLDataType.VARCHAR(30).nullable(false), this, "");

    /**
     * The column <code>money_transfer.transaction_type.description</code>.
     */
    public final TableField<TransactionTypeRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>money_transfer.transaction_type.name</code>.
     */
    public final TableField<TransactionTypeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100), this, "");

    private TransactionType(Name alias, Table<TransactionTypeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TransactionType(Name alias, Table<TransactionTypeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>money_transfer.transaction_type</code> table
     * reference
     */
    public TransactionType(String alias) {
        this(DSL.name(alias), TRANSACTION_TYPE);
    }

    /**
     * Create an aliased <code>money_transfer.transaction_type</code> table
     * reference
     */
    public TransactionType(Name alias) {
        this(alias, TRANSACTION_TYPE);
    }

    /**
     * Create a <code>money_transfer.transaction_type</code> table reference
     */
    public TransactionType() {
        this(DSL.name("transaction_type"), null);
    }

    public <O extends Record> TransactionType(Table<O> path, ForeignKey<O, TransactionTypeRecord> childPath, InverseForeignKey<O, TransactionTypeRecord> parentPath) {
        super(path, childPath, parentPath, TRANSACTION_TYPE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TransactionTypePath extends TransactionType implements Path<TransactionTypeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TransactionTypePath(Table<O> path, ForeignKey<O, TransactionTypeRecord> childPath, InverseForeignKey<O, TransactionTypeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TransactionTypePath(Name alias, Table<TransactionTypeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TransactionTypePath as(String alias) {
            return new TransactionTypePath(DSL.name(alias), this);
        }

        @Override
        public TransactionTypePath as(Name alias) {
            return new TransactionTypePath(alias, this);
        }

        @Override
        public TransactionTypePath as(Table<?> alias) {
            return new TransactionTypePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : MoneyTransfer.MONEY_TRANSFER;
    }

    @Override
    public Identity<TransactionTypeRecord, Long> getIdentity() {
        return (Identity<TransactionTypeRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<TransactionTypeRecord> getPrimaryKey() {
        return Keys.TRANSACTION_TYPE_PKEY;
    }

    @Override
    public List<UniqueKey<TransactionTypeRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.TRANSACTION_TYPE_TYPE_CODE_KEY);
    }

    private transient TransactionHistoryPath _transactionHistory;

    /**
     * Get the implicit to-many join path to the
     * <code>money_transfer.transaction_history</code> table
     */
    public TransactionHistoryPath transactionHistory() {
        if (_transactionHistory == null)
            _transactionHistory = new TransactionHistoryPath(this, null, Keys.TRANSACTION_HISTORY__TRANSACTION_TYPE_FK.getInverseKey());

        return _transactionHistory;
    }

    @Override
    public TransactionType as(String alias) {
        return new TransactionType(DSL.name(alias), this);
    }

    @Override
    public TransactionType as(Name alias) {
        return new TransactionType(alias, this);
    }

    @Override
    public TransactionType as(Table<?> alias) {
        return new TransactionType(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TransactionType rename(String name) {
        return new TransactionType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TransactionType rename(Name name) {
        return new TransactionType(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TransactionType rename(Table<?> name) {
        return new TransactionType(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TransactionType where(Condition condition) {
        return new TransactionType(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TransactionType where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TransactionType where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TransactionType where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TransactionType where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TransactionType where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TransactionType where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TransactionType where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TransactionType whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TransactionType whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
