/*
 * This file is generated by jOOQ.
 */
package jooq.money_transfer.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import jooq.money_transfer.Keys;
import jooq.money_transfer.MoneyTransfer;
import jooq.money_transfer.tables.records.TransactionStatusRecord;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TransactionStatus extends TableImpl<TransactionStatusRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>money_transfer.transaction_status</code>
     */
    public static final TransactionStatus TRANSACTION_STATUS = new TransactionStatus();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TransactionStatusRecord> getRecordType() {
        return TransactionStatusRecord.class;
    }

    /**
     * The column <code>money_transfer.transaction_status.id</code>.
     */
    public final TableField<TransactionStatusRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>money_transfer.transaction_status.status_code</code>.
     */
    public final TableField<TransactionStatusRecord, String> STATUS_CODE = createField(DSL.name("status_code"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>money_transfer.transaction_status.description</code>.
     */
    public final TableField<TransactionStatusRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>money_transfer.transaction_status.name</code>.
     */
    public final TableField<TransactionStatusRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(20), this, "");

    private TransactionStatus(Name alias, Table<TransactionStatusRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TransactionStatus(Name alias, Table<TransactionStatusRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>money_transfer.transaction_status</code> table
     * reference
     */
    public TransactionStatus(String alias) {
        this(DSL.name(alias), TRANSACTION_STATUS);
    }

    /**
     * Create an aliased <code>money_transfer.transaction_status</code> table
     * reference
     */
    public TransactionStatus(Name alias) {
        this(alias, TRANSACTION_STATUS);
    }

    /**
     * Create a <code>money_transfer.transaction_status</code> table reference
     */
    public TransactionStatus() {
        this(DSL.name("transaction_status"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : MoneyTransfer.MONEY_TRANSFER;
    }

    @Override
    public Identity<TransactionStatusRecord, Long> getIdentity() {
        return (Identity<TransactionStatusRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<TransactionStatusRecord> getPrimaryKey() {
        return Keys.TRANSACTION_STATUS_PKEY;
    }

    @Override
    public List<UniqueKey<TransactionStatusRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.TRANSACTION_STATUS_STATUS_CODE_KEY);
    }

    @Override
    public TransactionStatus as(String alias) {
        return new TransactionStatus(DSL.name(alias), this);
    }

    @Override
    public TransactionStatus as(Name alias) {
        return new TransactionStatus(alias, this);
    }

    @Override
    public TransactionStatus as(Table<?> alias) {
        return new TransactionStatus(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TransactionStatus rename(String name) {
        return new TransactionStatus(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TransactionStatus rename(Name name) {
        return new TransactionStatus(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TransactionStatus rename(Table<?> name) {
        return new TransactionStatus(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TransactionStatus where(Condition condition) {
        return new TransactionStatus(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TransactionStatus where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TransactionStatus where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TransactionStatus where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TransactionStatus where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TransactionStatus where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TransactionStatus where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TransactionStatus where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TransactionStatus whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TransactionStatus whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
