/*
 * This file is generated by jOOQ.
 */
package jooq.money_transfer.tables;


import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import jooq.money_transfer.Keys;
import jooq.money_transfer.MoneyTransfer;
import jooq.money_transfer.tables.Account.AccountPath;
import jooq.money_transfer.tables.CurrencyType.CurrencyTypePath;
import jooq.money_transfer.tables.TransactionStatus.TransactionStatusPath;
import jooq.money_transfer.tables.TransactionType.TransactionTypePath;
import jooq.money_transfer.tables.records.TransactionHistoryRecord;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TransactionHistory extends TableImpl<TransactionHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>money_transfer.transaction_history</code>
     */
    public static final TransactionHistory TRANSACTION_HISTORY = new TransactionHistory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TransactionHistoryRecord> getRecordType() {
        return TransactionHistoryRecord.class;
    }

    /**
     * The column <code>money_transfer.transaction_history.id</code>.
     */
    public final TableField<TransactionHistoryRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column
     * <code>money_transfer.transaction_history.from_account_id</code>.
     */
    public final TableField<TransactionHistoryRecord, Long> FROM_ACCOUNT_ID = createField(DSL.name("from_account_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>money_transfer.transaction_history.to_account_id</code>.
     */
    public final TableField<TransactionHistoryRecord, Long> TO_ACCOUNT_ID = createField(DSL.name("to_account_id"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>money_transfer.transaction_history.amount</code>.
     */
    public final TableField<TransactionHistoryRecord, BigDecimal> AMOUNT = createField(DSL.name("amount"), SQLDataType.NUMERIC.nullable(false), this, "");

    /**
     * The column <code>money_transfer.transaction_history.currency</code>.
     */
    public final TableField<TransactionHistoryRecord, Long> CURRENCY = createField(DSL.name("currency"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>money_transfer.transaction_history.type_id</code>.
     */
    public final TableField<TransactionHistoryRecord, Long> TYPE_ID = createField(DSL.name("type_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>money_transfer.transaction_history.status_id</code>.
     */
    public final TableField<TransactionHistoryRecord, Long> STATUS_ID = createField(DSL.name("status_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>money_transfer.transaction_history.created_at</code>.
     */
    public final TableField<TransactionHistoryRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>money_transfer.transaction_history.description</code>.
     */
    public final TableField<TransactionHistoryRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>money_transfer.transaction_history.terminal_code</code>.
     */
    public final TableField<TransactionHistoryRecord, String> TERMINAL_CODE = createField(DSL.name("terminal_code"), SQLDataType.VARCHAR(100), this, "");

    private TransactionHistory(Name alias, Table<TransactionHistoryRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TransactionHistory(Name alias, Table<TransactionHistoryRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>money_transfer.transaction_history</code> table
     * reference
     */
    public TransactionHistory(String alias) {
        this(DSL.name(alias), TRANSACTION_HISTORY);
    }

    /**
     * Create an aliased <code>money_transfer.transaction_history</code> table
     * reference
     */
    public TransactionHistory(Name alias) {
        this(alias, TRANSACTION_HISTORY);
    }

    /**
     * Create a <code>money_transfer.transaction_history</code> table reference
     */
    public TransactionHistory() {
        this(DSL.name("transaction_history"), null);
    }

    public <O extends Record> TransactionHistory(Table<O> path, ForeignKey<O, TransactionHistoryRecord> childPath, InverseForeignKey<O, TransactionHistoryRecord> parentPath) {
        super(path, childPath, parentPath, TRANSACTION_HISTORY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TransactionHistoryPath extends TransactionHistory implements Path<TransactionHistoryRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TransactionHistoryPath(Table<O> path, ForeignKey<O, TransactionHistoryRecord> childPath, InverseForeignKey<O, TransactionHistoryRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TransactionHistoryPath(Name alias, Table<TransactionHistoryRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TransactionHistoryPath as(String alias) {
            return new TransactionHistoryPath(DSL.name(alias), this);
        }

        @Override
        public TransactionHistoryPath as(Name alias) {
            return new TransactionHistoryPath(alias, this);
        }

        @Override
        public TransactionHistoryPath as(Table<?> alias) {
            return new TransactionHistoryPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : MoneyTransfer.MONEY_TRANSFER;
    }

    @Override
    public Identity<TransactionHistoryRecord, Long> getIdentity() {
        return (Identity<TransactionHistoryRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<TransactionHistoryRecord> getPrimaryKey() {
        return Keys.TRANSACTION_HISTORY_PK;
    }

    @Override
    public List<ForeignKey<TransactionHistoryRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TRANSACTION_HISTORY__CURRENCY_TYPE_FK, Keys.TRANSACTION_HISTORY__FROM_ACCOUNT_FK, Keys.TRANSACTION_HISTORY__TO_ACCOUNT_FK, Keys.TRANSACTION_HISTORY__TRANSACTION_STATUS_FK, Keys.TRANSACTION_HISTORY__TRANSACTION_TYPE_FK);
    }

    private transient CurrencyTypePath _currencyType;

    /**
     * Get the implicit join path to the
     * <code>money_transfer.currency_type</code> table.
     */
    public CurrencyTypePath currencyType() {
        if (_currencyType == null)
            _currencyType = new CurrencyTypePath(this, Keys.TRANSACTION_HISTORY__CURRENCY_TYPE_FK, null);

        return _currencyType;
    }

    private transient AccountPath _fromAccountFk;

    /**
     * Get the implicit join path to the <code>money_transfer.account</code>
     * table, via the <code>from_account_fk</code> key.
     */
    public AccountPath fromAccountFk() {
        if (_fromAccountFk == null)
            _fromAccountFk = new AccountPath(this, Keys.TRANSACTION_HISTORY__FROM_ACCOUNT_FK, null);

        return _fromAccountFk;
    }

    private transient AccountPath _toAccountFk;

    /**
     * Get the implicit join path to the <code>money_transfer.account</code>
     * table, via the <code>to_account_fk</code> key.
     */
    public AccountPath toAccountFk() {
        if (_toAccountFk == null)
            _toAccountFk = new AccountPath(this, Keys.TRANSACTION_HISTORY__TO_ACCOUNT_FK, null);

        return _toAccountFk;
    }

    private transient TransactionStatusPath _transactionStatus;

    /**
     * Get the implicit join path to the
     * <code>money_transfer.transaction_status</code> table.
     */
    public TransactionStatusPath transactionStatus() {
        if (_transactionStatus == null)
            _transactionStatus = new TransactionStatusPath(this, Keys.TRANSACTION_HISTORY__TRANSACTION_STATUS_FK, null);

        return _transactionStatus;
    }

    private transient TransactionTypePath _transactionType;

    /**
     * Get the implicit join path to the
     * <code>money_transfer.transaction_type</code> table.
     */
    public TransactionTypePath transactionType() {
        if (_transactionType == null)
            _transactionType = new TransactionTypePath(this, Keys.TRANSACTION_HISTORY__TRANSACTION_TYPE_FK, null);

        return _transactionType;
    }

    @Override
    public List<Check<TransactionHistoryRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("transaction_history_amount_check"), "((amount > (0)::numeric))", true)
        );
    }

    @Override
    public TransactionHistory as(String alias) {
        return new TransactionHistory(DSL.name(alias), this);
    }

    @Override
    public TransactionHistory as(Name alias) {
        return new TransactionHistory(alias, this);
    }

    @Override
    public TransactionHistory as(Table<?> alias) {
        return new TransactionHistory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TransactionHistory rename(String name) {
        return new TransactionHistory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TransactionHistory rename(Name name) {
        return new TransactionHistory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TransactionHistory rename(Table<?> name) {
        return new TransactionHistory(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TransactionHistory where(Condition condition) {
        return new TransactionHistory(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TransactionHistory where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TransactionHistory where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TransactionHistory where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TransactionHistory where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TransactionHistory where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TransactionHistory where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TransactionHistory where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TransactionHistory whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TransactionHistory whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
