/*
 * This file is generated by jOOQ.
 */
package jooq.money_transfer.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccountType implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String typeCode;
    private String description;
    private String name;

    public AccountType() {}

    public AccountType(AccountType value) {
        this.id = value.id;
        this.typeCode = value.typeCode;
        this.description = value.description;
        this.name = value.name;
    }

    public AccountType(
        Long id,
        String typeCode,
        String description,
        String name
    ) {
        this.id = id;
        this.typeCode = typeCode;
        this.description = description;
        this.name = name;
    }

    /**
     * Getter for <code>money_transfer.account_type.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>money_transfer.account_type.id</code>.
     */
    public AccountType setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>money_transfer.account_type.type_code</code>.
     */
    public String getTypeCode() {
        return this.typeCode;
    }

    /**
     * Setter for <code>money_transfer.account_type.type_code</code>.
     */
    public AccountType setTypeCode(String typeCode) {
        this.typeCode = typeCode;
        return this;
    }

    /**
     * Getter for <code>money_transfer.account_type.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>money_transfer.account_type.description</code>.
     */
    public AccountType setDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Getter for <code>money_transfer.account_type.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>money_transfer.account_type.name</code>.
     */
    public AccountType setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AccountType other = (AccountType) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AccountType (");

        sb.append(id);
        sb.append(", ").append(typeCode);
        sb.append(", ").append(description);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
