/*
 * This file is generated by jOOQ.
 */
package jooq.money_transfer.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Account implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long userAccountId;
    private String accountNumber;
    private BigDecimal balance;
    private LocalDateTime createdAt;
    private Long currency;
    private Long typeId;
    private Long statusId;
    private LocalDateTime closedAt;

    public Account() {}

    public Account(Account value) {
        this.id = value.id;
        this.userAccountId = value.userAccountId;
        this.accountNumber = value.accountNumber;
        this.balance = value.balance;
        this.createdAt = value.createdAt;
        this.currency = value.currency;
        this.typeId = value.typeId;
        this.statusId = value.statusId;
        this.closedAt = value.closedAt;
    }

    public Account(
        Long id,
        Long userAccountId,
        String accountNumber,
        BigDecimal balance,
        LocalDateTime createdAt,
        Long currency,
        Long typeId,
        Long statusId,
        LocalDateTime closedAt
    ) {
        this.id = id;
        this.userAccountId = userAccountId;
        this.accountNumber = accountNumber;
        this.balance = balance;
        this.createdAt = createdAt;
        this.currency = currency;
        this.typeId = typeId;
        this.statusId = statusId;
        this.closedAt = closedAt;
    }

    /**
     * Getter for <code>money_transfer.account.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>money_transfer.account.id</code>.
     */
    public Account setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>money_transfer.account.user_account_id</code>.
     */
    public Long getUserAccountId() {
        return this.userAccountId;
    }

    /**
     * Setter for <code>money_transfer.account.user_account_id</code>.
     */
    public Account setUserAccountId(Long userAccountId) {
        this.userAccountId = userAccountId;
        return this;
    }

    /**
     * Getter for <code>money_transfer.account.account_number</code>.
     */
    public String getAccountNumber() {
        return this.accountNumber;
    }

    /**
     * Setter for <code>money_transfer.account.account_number</code>.
     */
    public Account setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
        return this;
    }

    /**
     * Getter for <code>money_transfer.account.balance</code>.
     */
    public BigDecimal getBalance() {
        return this.balance;
    }

    /**
     * Setter for <code>money_transfer.account.balance</code>.
     */
    public Account setBalance(BigDecimal balance) {
        this.balance = balance;
        return this;
    }

    /**
     * Getter for <code>money_transfer.account.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>money_transfer.account.created_at</code>.
     */
    public Account setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>money_transfer.account.currency</code>.
     */
    public Long getCurrency() {
        return this.currency;
    }

    /**
     * Setter for <code>money_transfer.account.currency</code>.
     */
    public Account setCurrency(Long currency) {
        this.currency = currency;
        return this;
    }

    /**
     * Getter for <code>money_transfer.account.type_id</code>.
     */
    public Long getTypeId() {
        return this.typeId;
    }

    /**
     * Setter for <code>money_transfer.account.type_id</code>.
     */
    public Account setTypeId(Long typeId) {
        this.typeId = typeId;
        return this;
    }

    /**
     * Getter for <code>money_transfer.account.status_id</code>.
     */
    public Long getStatusId() {
        return this.statusId;
    }

    /**
     * Setter for <code>money_transfer.account.status_id</code>.
     */
    public Account setStatusId(Long statusId) {
        this.statusId = statusId;
        return this;
    }

    /**
     * Getter for <code>money_transfer.account.closed_at</code>.
     */
    public LocalDateTime getClosedAt() {
        return this.closedAt;
    }

    /**
     * Setter for <code>money_transfer.account.closed_at</code>.
     */
    public Account setClosedAt(LocalDateTime closedAt) {
        this.closedAt = closedAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Account other = (Account) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Account (");

        sb.append(id);
        sb.append(", ").append(userAccountId);
        sb.append(", ").append(accountNumber);
        sb.append(", ").append(balance);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(currency);
        sb.append(", ").append(typeId);
        sb.append(", ").append(statusId);
        sb.append(", ").append(closedAt);

        sb.append(")");
        return sb.toString();
    }
}
