/*
 * This file is generated by jOOQ.
 */
package jooq.money_transfer.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CurrencyType implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String currencyCode;
    private String description;

    public CurrencyType() {}

    public CurrencyType(CurrencyType value) {
        this.id = value.id;
        this.currencyCode = value.currencyCode;
        this.description = value.description;
    }

    public CurrencyType(
        Long id,
        String currencyCode,
        String description
    ) {
        this.id = id;
        this.currencyCode = currencyCode;
        this.description = description;
    }

    /**
     * Getter for <code>money_transfer.currency_type.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>money_transfer.currency_type.id</code>.
     */
    public CurrencyType setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>money_transfer.currency_type.currency_code</code>.
     */
    public String getCurrencyCode() {
        return this.currencyCode;
    }

    /**
     * Setter for <code>money_transfer.currency_type.currency_code</code>.
     */
    public CurrencyType setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
        return this;
    }

    /**
     * Getter for <code>money_transfer.currency_type.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>money_transfer.currency_type.description</code>.
     */
    public CurrencyType setDescription(String description) {
        this.description = description;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CurrencyType other = (CurrencyType) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CurrencyType (");

        sb.append(id);
        sb.append(", ").append(currencyCode);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
