/*
 * This file is generated by jOOQ.
 */
package jooq.money_transfer.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TransactionHistory implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long fromAccountId;
    private Long toAccountId;
    private BigDecimal amount;
    private Long currency;
    private Long typeId;
    private Long statusId;
    private LocalDateTime createdAt;
    private String description;
    private String outgoingCode;
    private String statusName;
    private String currencyName;
    private String typeName;

    public TransactionHistory() {}

    public TransactionHistory(TransactionHistory value) {
        this.id = value.id;
        this.fromAccountId = value.fromAccountId;
        this.toAccountId = value.toAccountId;
        this.amount = value.amount;
        this.currency = value.currency;
        this.typeId = value.typeId;
        this.statusId = value.statusId;
        this.createdAt = value.createdAt;
        this.description = value.description;
        this.outgoingCode = value.outgoingCode;
        this.statusName = value.statusName;
        this.currencyName = value.currencyName;
        this.typeName = value.typeName;
    }

    public TransactionHistory(
        Long id,
        Long fromAccountId,
        Long toAccountId,
        BigDecimal amount,
        Long currency,
        Long typeId,
        Long statusId,
        LocalDateTime createdAt,
        String description,
        String outgoingCode,
        String statusName,
        String currencyName,
        String typeName
    ) {
        this.id = id;
        this.fromAccountId = fromAccountId;
        this.toAccountId = toAccountId;
        this.amount = amount;
        this.currency = currency;
        this.typeId = typeId;
        this.statusId = statusId;
        this.createdAt = createdAt;
        this.description = description;
        this.outgoingCode = outgoingCode;
        this.statusName = statusName;
        this.currencyName = currencyName;
        this.typeName = typeName;
    }

    /**
     * Getter for <code>money_transfer.transaction_history.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>money_transfer.transaction_history.id</code>.
     */
    public TransactionHistory setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for
     * <code>money_transfer.transaction_history.from_account_id</code>.
     */
    public Long getFromAccountId() {
        return this.fromAccountId;
    }

    /**
     * Setter for
     * <code>money_transfer.transaction_history.from_account_id</code>.
     */
    public TransactionHistory setFromAccountId(Long fromAccountId) {
        this.fromAccountId = fromAccountId;
        return this;
    }

    /**
     * Getter for <code>money_transfer.transaction_history.to_account_id</code>.
     */
    public Long getToAccountId() {
        return this.toAccountId;
    }

    /**
     * Setter for <code>money_transfer.transaction_history.to_account_id</code>.
     */
    public TransactionHistory setToAccountId(Long toAccountId) {
        this.toAccountId = toAccountId;
        return this;
    }

    /**
     * Getter for <code>money_transfer.transaction_history.amount</code>.
     */
    public BigDecimal getAmount() {
        return this.amount;
    }

    /**
     * Setter for <code>money_transfer.transaction_history.amount</code>.
     */
    public TransactionHistory setAmount(BigDecimal amount) {
        this.amount = amount;
        return this;
    }

    /**
     * Getter for <code>money_transfer.transaction_history.currency</code>.
     */
    public Long getCurrency() {
        return this.currency;
    }

    /**
     * Setter for <code>money_transfer.transaction_history.currency</code>.
     */
    public TransactionHistory setCurrency(Long currency) {
        this.currency = currency;
        return this;
    }

    /**
     * Getter for <code>money_transfer.transaction_history.type_id</code>.
     */
    public Long getTypeId() {
        return this.typeId;
    }

    /**
     * Setter for <code>money_transfer.transaction_history.type_id</code>.
     */
    public TransactionHistory setTypeId(Long typeId) {
        this.typeId = typeId;
        return this;
    }

    /**
     * Getter for <code>money_transfer.transaction_history.status_id</code>.
     */
    public Long getStatusId() {
        return this.statusId;
    }

    /**
     * Setter for <code>money_transfer.transaction_history.status_id</code>.
     */
    public TransactionHistory setStatusId(Long statusId) {
        this.statusId = statusId;
        return this;
    }

    /**
     * Getter for <code>money_transfer.transaction_history.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>money_transfer.transaction_history.created_at</code>.
     */
    public TransactionHistory setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>money_transfer.transaction_history.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>money_transfer.transaction_history.description</code>.
     */
    public TransactionHistory setDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Getter for <code>money_transfer.transaction_history.outgoing_code</code>.
     */
    public String getOutgoingCode() {
        return this.outgoingCode;
    }

    /**
     * Setter for <code>money_transfer.transaction_history.outgoing_code</code>.
     */
    public TransactionHistory setOutgoingCode(String outgoingCode) {
        this.outgoingCode = outgoingCode;
        return this;
    }

    /**
     * Getter for <code>money_transfer.transaction_history.status_name</code>.
     */
    public String getStatusName() {
        return this.statusName;
    }

    /**
     * Setter for <code>money_transfer.transaction_history.status_name</code>.
     */
    public TransactionHistory setStatusName(String statusName) {
        this.statusName = statusName;
        return this;
    }

    /**
     * Getter for <code>money_transfer.transaction_history.currency_name</code>.
     */
    public String getCurrencyName() {
        return this.currencyName;
    }

    /**
     * Setter for <code>money_transfer.transaction_history.currency_name</code>.
     */
    public TransactionHistory setCurrencyName(String currencyName) {
        this.currencyName = currencyName;
        return this;
    }

    /**
     * Getter for <code>money_transfer.transaction_history.type_name</code>.
     */
    public String getTypeName() {
        return this.typeName;
    }

    /**
     * Setter for <code>money_transfer.transaction_history.type_name</code>.
     */
    public TransactionHistory setTypeName(String typeName) {
        this.typeName = typeName;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TransactionHistory other = (TransactionHistory) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TransactionHistory (");

        sb.append(id);
        sb.append(", ").append(fromAccountId);
        sb.append(", ").append(toAccountId);
        sb.append(", ").append(amount);
        sb.append(", ").append(currency);
        sb.append(", ").append(typeId);
        sb.append(", ").append(statusId);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(description);
        sb.append(", ").append(outgoingCode);
        sb.append(", ").append(statusName);
        sb.append(", ").append(currencyName);
        sb.append(", ").append(typeName);

        sb.append(")");
        return sb.toString();
    }
}
