/*
 * This file is generated by jOOQ.
 */
package jooq.money_transfer.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TransactionStatus implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String statusCode;
    private String description;
    private String name;

    public TransactionStatus() {}

    public TransactionStatus(TransactionStatus value) {
        this.id = value.id;
        this.statusCode = value.statusCode;
        this.description = value.description;
        this.name = value.name;
    }

    public TransactionStatus(
        Long id,
        String statusCode,
        String description,
        String name
    ) {
        this.id = id;
        this.statusCode = statusCode;
        this.description = description;
        this.name = name;
    }

    /**
     * Getter for <code>money_transfer.transaction_status.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>money_transfer.transaction_status.id</code>.
     */
    public TransactionStatus setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>money_transfer.transaction_status.status_code</code>.
     */
    public String getStatusCode() {
        return this.statusCode;
    }

    /**
     * Setter for <code>money_transfer.transaction_status.status_code</code>.
     */
    public TransactionStatus setStatusCode(String statusCode) {
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Getter for <code>money_transfer.transaction_status.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>money_transfer.transaction_status.description</code>.
     */
    public TransactionStatus setDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Getter for <code>money_transfer.transaction_status.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>money_transfer.transaction_status.name</code>.
     */
    public TransactionStatus setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TransactionStatus other = (TransactionStatus) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TransactionStatus (");

        sb.append(id);
        sb.append(", ").append(statusCode);
        sb.append(", ").append(description);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
