/*
 * This file is generated by jOOQ.
 */
package jooq.auth.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Role implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String sysName;
    private String description;
    private Boolean isActual;

    public Role() {}

    public Role(Role value) {
        this.id = value.id;
        this.sysName = value.sysName;
        this.description = value.description;
        this.isActual = value.isActual;
    }

    public Role(
        Long id,
        String sysName,
        String description,
        Boolean isActual
    ) {
        this.id = id;
        this.sysName = sysName;
        this.description = description;
        this.isActual = isActual;
    }

    /**
     * Getter for <code>auth.role.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>auth.role.id</code>.
     */
    public Role setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>auth.role.sys_name</code>.
     */
    public String getSysName() {
        return this.sysName;
    }

    /**
     * Setter for <code>auth.role.sys_name</code>.
     */
    public Role setSysName(String sysName) {
        this.sysName = sysName;
        return this;
    }

    /**
     * Getter for <code>auth.role.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>auth.role.description</code>.
     */
    public Role setDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Getter for <code>auth.role.is_actual</code>.
     */
    public Boolean getIsActual() {
        return this.isActual;
    }

    /**
     * Setter for <code>auth.role.is_actual</code>.
     */
    public Role setIsActual(Boolean isActual) {
        this.isActual = isActual;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Role other = (Role) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Role (");

        sb.append(id);
        sb.append(", ").append(sysName);
        sb.append(", ").append(description);
        sb.append(", ").append(isActual);

        sb.append(")");
        return sb.toString();
    }
}
