/*
 * This file is generated by jOOQ.
 */
package jooq.auth.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserAccount implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String username;
    private String fullName;
    private Boolean enabled;
    private String password;
    private String numberPhone;
    private Long roleId;

    public UserAccount() {}

    public UserAccount(UserAccount value) {
        this.id = value.id;
        this.username = value.username;
        this.fullName = value.fullName;
        this.enabled = value.enabled;
        this.password = value.password;
        this.numberPhone = value.numberPhone;
        this.roleId = value.roleId;
    }

    public UserAccount(
        Long id,
        String username,
        String fullName,
        Boolean enabled,
        String password,
        String numberPhone,
        Long roleId
    ) {
        this.id = id;
        this.username = username;
        this.fullName = fullName;
        this.enabled = enabled;
        this.password = password;
        this.numberPhone = numberPhone;
        this.roleId = roleId;
    }

    /**
     * Getter for <code>auth.user_account.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>auth.user_account.id</code>.
     */
    public UserAccount setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>auth.user_account.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>auth.user_account.username</code>.
     */
    public UserAccount setUsername(String username) {
        this.username = username;
        return this;
    }

    /**
     * Getter for <code>auth.user_account.full_name</code>.
     */
    public String getFullName() {
        return this.fullName;
    }

    /**
     * Setter for <code>auth.user_account.full_name</code>.
     */
    public UserAccount setFullName(String fullName) {
        this.fullName = fullName;
        return this;
    }

    /**
     * Getter for <code>auth.user_account.enabled</code>.
     */
    public Boolean getEnabled() {
        return this.enabled;
    }

    /**
     * Setter for <code>auth.user_account.enabled</code>.
     */
    public UserAccount setEnabled(Boolean enabled) {
        this.enabled = enabled;
        return this;
    }

    /**
     * Getter for <code>auth.user_account.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>auth.user_account.password</code>.
     */
    public UserAccount setPassword(String password) {
        this.password = password;
        return this;
    }

    /**
     * Getter for <code>auth.user_account.number_phone</code>.
     */
    public String getNumberPhone() {
        return this.numberPhone;
    }

    /**
     * Setter for <code>auth.user_account.number_phone</code>.
     */
    public UserAccount setNumberPhone(String numberPhone) {
        this.numberPhone = numberPhone;
        return this;
    }

    /**
     * Getter for <code>auth.user_account.role_id</code>.
     */
    public Long getRoleId() {
        return this.roleId;
    }

    /**
     * Setter for <code>auth.user_account.role_id</code>.
     */
    public UserAccount setRoleId(Long roleId) {
        this.roleId = roleId;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserAccount other = (UserAccount) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserAccount (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(fullName);
        sb.append(", ").append(enabled);
        sb.append(", ").append(password);
        sb.append(", ").append(numberPhone);
        sb.append(", ").append(roleId);

        sb.append(")");
        return sb.toString();
    }
}
