/*
 * This file is generated by jOOQ.
 */
package jooq.auth.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserData implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long userId;
    private String fullName;
    private LocalDate birthDate;
    private String country;
    private String numberPhone;
    private String passportSeries;
    private String passportNumber;
    private String passportIssuedBy;
    private LocalDate passportIssueDate;

    public UserData() {}

    public UserData(UserData value) {
        this.id = value.id;
        this.userId = value.userId;
        this.fullName = value.fullName;
        this.birthDate = value.birthDate;
        this.country = value.country;
        this.numberPhone = value.numberPhone;
        this.passportSeries = value.passportSeries;
        this.passportNumber = value.passportNumber;
        this.passportIssuedBy = value.passportIssuedBy;
        this.passportIssueDate = value.passportIssueDate;
    }

    public UserData(
        Long id,
        Long userId,
        String fullName,
        LocalDate birthDate,
        String country,
        String numberPhone,
        String passportSeries,
        String passportNumber,
        String passportIssuedBy,
        LocalDate passportIssueDate
    ) {
        this.id = id;
        this.userId = userId;
        this.fullName = fullName;
        this.birthDate = birthDate;
        this.country = country;
        this.numberPhone = numberPhone;
        this.passportSeries = passportSeries;
        this.passportNumber = passportNumber;
        this.passportIssuedBy = passportIssuedBy;
        this.passportIssueDate = passportIssueDate;
    }

    /**
     * Getter for <code>auth.user_data.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>auth.user_data.id</code>.
     */
    public UserData setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>auth.user_data.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>auth.user_data.user_id</code>.
     */
    public UserData setUserId(Long userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>auth.user_data.full_name</code>.
     */
    public String getFullName() {
        return this.fullName;
    }

    /**
     * Setter for <code>auth.user_data.full_name</code>.
     */
    public UserData setFullName(String fullName) {
        this.fullName = fullName;
        return this;
    }

    /**
     * Getter for <code>auth.user_data.birth_date</code>.
     */
    public LocalDate getBirthDate() {
        return this.birthDate;
    }

    /**
     * Setter for <code>auth.user_data.birth_date</code>.
     */
    public UserData setBirthDate(LocalDate birthDate) {
        this.birthDate = birthDate;
        return this;
    }

    /**
     * Getter for <code>auth.user_data.country</code>.
     */
    public String getCountry() {
        return this.country;
    }

    /**
     * Setter for <code>auth.user_data.country</code>.
     */
    public UserData setCountry(String country) {
        this.country = country;
        return this;
    }

    /**
     * Getter for <code>auth.user_data.number_phone</code>.
     */
    public String getNumberPhone() {
        return this.numberPhone;
    }

    /**
     * Setter for <code>auth.user_data.number_phone</code>.
     */
    public UserData setNumberPhone(String numberPhone) {
        this.numberPhone = numberPhone;
        return this;
    }

    /**
     * Getter for <code>auth.user_data.passport_series</code>.
     */
    public String getPassportSeries() {
        return this.passportSeries;
    }

    /**
     * Setter for <code>auth.user_data.passport_series</code>.
     */
    public UserData setPassportSeries(String passportSeries) {
        this.passportSeries = passportSeries;
        return this;
    }

    /**
     * Getter for <code>auth.user_data.passport_number</code>.
     */
    public String getPassportNumber() {
        return this.passportNumber;
    }

    /**
     * Setter for <code>auth.user_data.passport_number</code>.
     */
    public UserData setPassportNumber(String passportNumber) {
        this.passportNumber = passportNumber;
        return this;
    }

    /**
     * Getter for <code>auth.user_data.passport_issued_by</code>.
     */
    public String getPassportIssuedBy() {
        return this.passportIssuedBy;
    }

    /**
     * Setter for <code>auth.user_data.passport_issued_by</code>.
     */
    public UserData setPassportIssuedBy(String passportIssuedBy) {
        this.passportIssuedBy = passportIssuedBy;
        return this;
    }

    /**
     * Getter for <code>auth.user_data.passport_issue_date</code>.
     */
    public LocalDate getPassportIssueDate() {
        return this.passportIssueDate;
    }

    /**
     * Setter for <code>auth.user_data.passport_issue_date</code>.
     */
    public UserData setPassportIssueDate(LocalDate passportIssueDate) {
        this.passportIssueDate = passportIssueDate;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserData other = (UserData) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserData (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(fullName);
        sb.append(", ").append(birthDate);
        sb.append(", ").append(country);
        sb.append(", ").append(numberPhone);
        sb.append(", ").append(passportSeries);
        sb.append(", ").append(passportNumber);
        sb.append(", ").append(passportIssuedBy);
        sb.append(", ").append(passportIssueDate);

        sb.append(")");
        return sb.toString();
    }
}
