/*
 * This file is generated by jOOQ.
 */
package jooq.money_transfer.tables.records;


import jooq.money_transfer.tables.AccountType;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccountTypeRecord extends UpdatableRecordImpl<AccountTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>money_transfer.account_type.id</code>.
     */
    public AccountTypeRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.account_type.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>money_transfer.account_type.type_code</code>.
     */
    public AccountTypeRecord setTypeCode(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.account_type.type_code</code>.
     */
    public String getTypeCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>money_transfer.account_type.description</code>.
     */
    public AccountTypeRecord setDescription(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.account_type.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>money_transfer.account_type.name</code>.
     */
    public AccountTypeRecord setName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.account_type.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountTypeRecord
     */
    public AccountTypeRecord() {
        super(AccountType.ACCOUNT_TYPE);
    }

    /**
     * Create a detached, initialised AccountTypeRecord
     */
    public AccountTypeRecord(Long id, String typeCode, String description, String name) {
        super(AccountType.ACCOUNT_TYPE);

        setId(id);
        setTypeCode(typeCode);
        setDescription(description);
        setName(name);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised AccountTypeRecord
     */
    public AccountTypeRecord(jooq.money_transfer.tables.pojos.AccountType value) {
        super(AccountType.ACCOUNT_TYPE);

        if (value != null) {
            setId(value.getId());
            setTypeCode(value.getTypeCode());
            setDescription(value.getDescription());
            setName(value.getName());
            resetTouchedOnNotNull();
        }
    }
}
