/*
 * This file is generated by jOOQ.
 */
package jooq.money_transfer.tables.records;


import jooq.money_transfer.tables.AccountStatus;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccountStatusRecord extends UpdatableRecordImpl<AccountStatusRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>money_transfer.account_status.id</code>.
     */
    public AccountStatusRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.account_status.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>money_transfer.account_status.status_code</code>.
     */
    public AccountStatusRecord setStatusCode(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.account_status.status_code</code>.
     */
    public String getStatusCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>money_transfer.account_status.description</code>.
     */
    public AccountStatusRecord setDescription(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.account_status.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>money_transfer.account_status.name</code>.
     */
    public AccountStatusRecord setName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.account_status.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountStatusRecord
     */
    public AccountStatusRecord() {
        super(AccountStatus.ACCOUNT_STATUS);
    }

    /**
     * Create a detached, initialised AccountStatusRecord
     */
    public AccountStatusRecord(Long id, String statusCode, String description, String name) {
        super(AccountStatus.ACCOUNT_STATUS);

        setId(id);
        setStatusCode(statusCode);
        setDescription(description);
        setName(name);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised AccountStatusRecord
     */
    public AccountStatusRecord(jooq.money_transfer.tables.pojos.AccountStatus value) {
        super(AccountStatus.ACCOUNT_STATUS);

        if (value != null) {
            setId(value.getId());
            setStatusCode(value.getStatusCode());
            setDescription(value.getDescription());
            setName(value.getName());
            resetTouchedOnNotNull();
        }
    }
}
