/*
 * This file is generated by jOOQ.
 */
package jooq.money_transfer.tables.records;


import java.math.BigDecimal;
import java.time.LocalDateTime;

import jooq.money_transfer.tables.Account;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccountRecord extends UpdatableRecordImpl<AccountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>money_transfer.account.id</code>.
     */
    public AccountRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.account.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>money_transfer.account.user_account_id</code>.
     */
    public AccountRecord setUserAccountId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.account.user_account_id</code>.
     */
    public Long getUserAccountId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>money_transfer.account.account_number</code>.
     */
    public AccountRecord setAccountNumber(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.account.account_number</code>.
     */
    public String getAccountNumber() {
        return (String) get(2);
    }

    /**
     * Setter for <code>money_transfer.account.currency</code>.
     */
    public AccountRecord setCurrency(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.account.currency</code>.
     */
    public Long getCurrency() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>money_transfer.account.balance</code>.
     */
    public AccountRecord setBalance(BigDecimal value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.account.balance</code>.
     */
    public BigDecimal getBalance() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>money_transfer.account.created_at</code>.
     */
    public AccountRecord setCreatedAt(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.account.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>money_transfer.account.type_id</code>.
     */
    public AccountRecord setTypeId(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.account.type_id</code>.
     */
    public Long getTypeId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>money_transfer.account.status_id</code>.
     */
    public AccountRecord setStatusId(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.account.status_id</code>.
     */
    public Long getStatusId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>money_transfer.account.closed_at</code>.
     */
    public AccountRecord setClosedAt(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.account.closed_at</code>.
     */
    public LocalDateTime getClosedAt() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountRecord
     */
    public AccountRecord() {
        super(Account.ACCOUNT);
    }

    /**
     * Create a detached, initialised AccountRecord
     */
    public AccountRecord(Long id, Long userAccountId, String accountNumber, Long currency, BigDecimal balance, LocalDateTime createdAt, Long typeId, Long statusId, LocalDateTime closedAt) {
        super(Account.ACCOUNT);

        setId(id);
        setUserAccountId(userAccountId);
        setAccountNumber(accountNumber);
        setCurrency(currency);
        setBalance(balance);
        setCreatedAt(createdAt);
        setTypeId(typeId);
        setStatusId(statusId);
        setClosedAt(closedAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised AccountRecord
     */
    public AccountRecord(jooq.money_transfer.tables.pojos.Account value) {
        super(Account.ACCOUNT);

        if (value != null) {
            setId(value.getId());
            setUserAccountId(value.getUserAccountId());
            setAccountNumber(value.getAccountNumber());
            setCurrency(value.getCurrency());
            setBalance(value.getBalance());
            setCreatedAt(value.getCreatedAt());
            setTypeId(value.getTypeId());
            setStatusId(value.getStatusId());
            setClosedAt(value.getClosedAt());
            resetTouchedOnNotNull();
        }
    }
}
