/*
 * This file is generated by jOOQ.
 */
package jooq.money_transfer.tables.records;


import jooq.money_transfer.tables.CurrencyType;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CurrencyTypeRecord extends UpdatableRecordImpl<CurrencyTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>money_transfer.currency_type.id</code>.
     */
    public CurrencyTypeRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.currency_type.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>money_transfer.currency_type.currency_code</code>.
     */
    public CurrencyTypeRecord setCurrencyCode(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.currency_type.currency_code</code>.
     */
    public String getCurrencyCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>money_transfer.currency_type.description</code>.
     */
    public CurrencyTypeRecord setDescription(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.currency_type.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>money_transfer.currency_type.name</code>.
     */
    public CurrencyTypeRecord setName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.currency_type.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CurrencyTypeRecord
     */
    public CurrencyTypeRecord() {
        super(CurrencyType.CURRENCY_TYPE);
    }

    /**
     * Create a detached, initialised CurrencyTypeRecord
     */
    public CurrencyTypeRecord(Long id, String currencyCode, String description, String name) {
        super(CurrencyType.CURRENCY_TYPE);

        setId(id);
        setCurrencyCode(currencyCode);
        setDescription(description);
        setName(name);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised CurrencyTypeRecord
     */
    public CurrencyTypeRecord(jooq.money_transfer.tables.pojos.CurrencyType value) {
        super(CurrencyType.CURRENCY_TYPE);

        if (value != null) {
            setId(value.getId());
            setCurrencyCode(value.getCurrencyCode());
            setDescription(value.getDescription());
            setName(value.getName());
            resetTouchedOnNotNull();
        }
    }
}
