/*
 * This file is generated by jOOQ.
 */
package jooq.money_transfer.tables.records;


import java.math.BigDecimal;
import java.time.LocalDateTime;

import jooq.money_transfer.tables.TransactionHistory;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TransactionHistoryRecord extends UpdatableRecordImpl<TransactionHistoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>money_transfer.transaction_history.id</code>.
     */
    public TransactionHistoryRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.transaction_history.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>money_transfer.transaction_history.from_account_id</code>.
     */
    public TransactionHistoryRecord setFromAccountId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for
     * <code>money_transfer.transaction_history.from_account_id</code>.
     */
    public Long getFromAccountId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>money_transfer.transaction_history.to_account_id</code>.
     */
    public TransactionHistoryRecord setToAccountId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.transaction_history.to_account_id</code>.
     */
    public Long getToAccountId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>money_transfer.transaction_history.amount</code>.
     */
    public TransactionHistoryRecord setAmount(BigDecimal value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.transaction_history.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>money_transfer.transaction_history.currency</code>.
     */
    public TransactionHistoryRecord setCurrency(Long value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.transaction_history.currency</code>.
     */
    public Long getCurrency() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>money_transfer.transaction_history.type_id</code>.
     */
    public TransactionHistoryRecord setTypeId(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.transaction_history.type_id</code>.
     */
    public Long getTypeId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>money_transfer.transaction_history.status_id</code>.
     */
    public TransactionHistoryRecord setStatusId(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.transaction_history.status_id</code>.
     */
    public Long getStatusId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>money_transfer.transaction_history.created_at</code>.
     */
    public TransactionHistoryRecord setCreatedAt(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.transaction_history.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>money_transfer.transaction_history.description</code>.
     */
    public TransactionHistoryRecord setDescription(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.transaction_history.description</code>.
     */
    public String getDescription() {
        return (String) get(8);
    }

    /**
     * Setter for <code>money_transfer.transaction_history.outgoing_code</code>.
     */
    public TransactionHistoryRecord setOutgoingCode(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.transaction_history.outgoing_code</code>.
     */
    public String getOutgoingCode() {
        return (String) get(9);
    }

    /**
     * Setter for <code>money_transfer.transaction_history.status_name</code>.
     */
    public TransactionHistoryRecord setStatusName(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.transaction_history.status_name</code>.
     */
    public String getStatusName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>money_transfer.transaction_history.currency_name</code>.
     */
    public TransactionHistoryRecord setCurrencyName(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.transaction_history.currency_name</code>.
     */
    public String getCurrencyName() {
        return (String) get(11);
    }

    /**
     * Setter for <code>money_transfer.transaction_history.type_name</code>.
     */
    public TransactionHistoryRecord setTypeName(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.transaction_history.type_name</code>.
     */
    public String getTypeName() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransactionHistoryRecord
     */
    public TransactionHistoryRecord() {
        super(TransactionHistory.TRANSACTION_HISTORY);
    }

    /**
     * Create a detached, initialised TransactionHistoryRecord
     */
    public TransactionHistoryRecord(Long id, Long fromAccountId, Long toAccountId, BigDecimal amount, Long currency, Long typeId, Long statusId, LocalDateTime createdAt, String description, String outgoingCode, String statusName, String currencyName, String typeName) {
        super(TransactionHistory.TRANSACTION_HISTORY);

        setId(id);
        setFromAccountId(fromAccountId);
        setToAccountId(toAccountId);
        setAmount(amount);
        setCurrency(currency);
        setTypeId(typeId);
        setStatusId(statusId);
        setCreatedAt(createdAt);
        setDescription(description);
        setOutgoingCode(outgoingCode);
        setStatusName(statusName);
        setCurrencyName(currencyName);
        setTypeName(typeName);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised TransactionHistoryRecord
     */
    public TransactionHistoryRecord(jooq.money_transfer.tables.pojos.TransactionHistory value) {
        super(TransactionHistory.TRANSACTION_HISTORY);

        if (value != null) {
            setId(value.getId());
            setFromAccountId(value.getFromAccountId());
            setToAccountId(value.getToAccountId());
            setAmount(value.getAmount());
            setCurrency(value.getCurrency());
            setTypeId(value.getTypeId());
            setStatusId(value.getStatusId());
            setCreatedAt(value.getCreatedAt());
            setDescription(value.getDescription());
            setOutgoingCode(value.getOutgoingCode());
            setStatusName(value.getStatusName());
            setCurrencyName(value.getCurrencyName());
            setTypeName(value.getTypeName());
            resetTouchedOnNotNull();
        }
    }
}
