/*
 * This file is generated by jOOQ.
 */
package jooq.money_transfer.tables.records;


import jooq.money_transfer.tables.TransactionType;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TransactionTypeRecord extends UpdatableRecordImpl<TransactionTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>money_transfer.transaction_type.id</code>.
     */
    public TransactionTypeRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.transaction_type.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>money_transfer.transaction_type.type_code</code>.
     */
    public TransactionTypeRecord setTypeCode(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.transaction_type.type_code</code>.
     */
    public String getTypeCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>money_transfer.transaction_type.description</code>.
     */
    public TransactionTypeRecord setDescription(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.transaction_type.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>money_transfer.transaction_type.name</code>.
     */
    public TransactionTypeRecord setName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>money_transfer.transaction_type.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransactionTypeRecord
     */
    public TransactionTypeRecord() {
        super(TransactionType.TRANSACTION_TYPE);
    }

    /**
     * Create a detached, initialised TransactionTypeRecord
     */
    public TransactionTypeRecord(Long id, String typeCode, String description, String name) {
        super(TransactionType.TRANSACTION_TYPE);

        setId(id);
        setTypeCode(typeCode);
        setDescription(description);
        setName(name);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised TransactionTypeRecord
     */
    public TransactionTypeRecord(jooq.money_transfer.tables.pojos.TransactionType value) {
        super(TransactionType.TRANSACTION_TYPE);

        if (value != null) {
            setId(value.getId());
            setTypeCode(value.getTypeCode());
            setDescription(value.getDescription());
            setName(value.getName());
            resetTouchedOnNotNull();
        }
    }
}
