/*
 * This file is generated by jOOQ.
 */
package jooq.money_transfer;


import jooq.auth.tables.UserAccount;
import jooq.auth.tables.records.UserAccountRecord;
import jooq.money_transfer.tables.Account;
import jooq.money_transfer.tables.TransactionHistory;
import jooq.money_transfer.tables.TransactionStatus;
import jooq.money_transfer.tables.TransactionType;
import jooq.money_transfer.tables.records.AccountRecord;
import jooq.money_transfer.tables.records.TransactionHistoryRecord;
import jooq.money_transfer.tables.records.TransactionStatusRecord;
import jooq.money_transfer.tables.records.TransactionTypeRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * money_transfer.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountRecord> ACCOUNT_ACCOUNT_NUMBER_KEY = Internal.createUniqueKey(Account.ACCOUNT, DSL.name("account_account_number_key"), new TableField[] { Account.ACCOUNT.ACCOUNT_NUMBER }, true);
    public static final UniqueKey<AccountRecord> ACCOUNT_PK = Internal.createUniqueKey(Account.ACCOUNT, DSL.name("account_pk"), new TableField[] { Account.ACCOUNT.ID }, true);
    public static final UniqueKey<TransactionHistoryRecord> TRANSACTION_HISTORY_PK = Internal.createUniqueKey(TransactionHistory.TRANSACTION_HISTORY, DSL.name("transaction_history_pk"), new TableField[] { TransactionHistory.TRANSACTION_HISTORY.ID }, true);
    public static final UniqueKey<TransactionStatusRecord> TRANSACTION_STATUS_PKEY = Internal.createUniqueKey(TransactionStatus.TRANSACTION_STATUS, DSL.name("transaction_status_pkey"), new TableField[] { TransactionStatus.TRANSACTION_STATUS.ID }, true);
    public static final UniqueKey<TransactionStatusRecord> TRANSACTION_STATUS_STATUS_CODE_KEY = Internal.createUniqueKey(TransactionStatus.TRANSACTION_STATUS, DSL.name("transaction_status_status_code_key"), new TableField[] { TransactionStatus.TRANSACTION_STATUS.STATUS_CODE }, true);
    public static final UniqueKey<TransactionTypeRecord> TRANSACTION_TYPE_PKEY = Internal.createUniqueKey(TransactionType.TRANSACTION_TYPE, DSL.name("transaction_type_pkey"), new TableField[] { TransactionType.TRANSACTION_TYPE.ID }, true);
    public static final UniqueKey<TransactionTypeRecord> TRANSACTION_TYPE_TYPE_CODE_KEY = Internal.createUniqueKey(TransactionType.TRANSACTION_TYPE, DSL.name("transaction_type_type_code_key"), new TableField[] { TransactionType.TRANSACTION_TYPE.TYPE_CODE }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AccountRecord, UserAccountRecord> ACCOUNT__USER_ACCOUNT_FK1 = Internal.createForeignKey(Account.ACCOUNT, DSL.name("user_account_fk1"), new TableField[] { Account.ACCOUNT.USER_ACCOUNT_ID }, jooq.auth.Keys.USER_ACCOUNT_PK, new TableField[] { UserAccount.USER_ACCOUNT.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<TransactionHistoryRecord, AccountRecord> TRANSACTION_HISTORY__FROM_ACCOUNT_FK = Internal.createForeignKey(TransactionHistory.TRANSACTION_HISTORY, DSL.name("from_account_fk"), new TableField[] { TransactionHistory.TRANSACTION_HISTORY.FROM_ACCOUNT_ID }, Keys.ACCOUNT_PK, new TableField[] { Account.ACCOUNT.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<TransactionHistoryRecord, AccountRecord> TRANSACTION_HISTORY__TO_ACCOUNT_FK = Internal.createForeignKey(TransactionHistory.TRANSACTION_HISTORY, DSL.name("to_account_fk"), new TableField[] { TransactionHistory.TRANSACTION_HISTORY.TO_ACCOUNT_ID }, Keys.ACCOUNT_PK, new TableField[] { Account.ACCOUNT.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<TransactionHistoryRecord, TransactionStatusRecord> TRANSACTION_HISTORY__TRANSACTION_STATUS_FK = Internal.createForeignKey(TransactionHistory.TRANSACTION_HISTORY, DSL.name("transaction_status_fk"), new TableField[] { TransactionHistory.TRANSACTION_HISTORY.STATUS_ID }, Keys.TRANSACTION_STATUS_PKEY, new TableField[] { TransactionStatus.TRANSACTION_STATUS.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<TransactionHistoryRecord, TransactionTypeRecord> TRANSACTION_HISTORY__TRANSACTION_TYPE_FK = Internal.createForeignKey(TransactionHistory.TRANSACTION_HISTORY, DSL.name("transaction_type_fk"), new TableField[] { TransactionHistory.TRANSACTION_HISTORY.TYPE_ID }, Keys.TRANSACTION_TYPE_PKEY, new TableField[] { TransactionType.TRANSACTION_TYPE.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
}
