/*
 * This file is generated by jOOQ.
 */
package jooq.money_transfer;


import java.util.Arrays;
import java.util.List;

import jooq.DefaultCatalog;
import jooq.money_transfer.tables.Account;
import jooq.money_transfer.tables.TransactionHistory;
import jooq.money_transfer.tables.TransactionStatus;
import jooq.money_transfer.tables.TransactionType;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MoneyTransfer extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>money_transfer</code>
     */
    public static final MoneyTransfer MONEY_TRANSFER = new MoneyTransfer();

    /**
     * The table <code>money_transfer.account</code>.
     */
    public final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>money_transfer.transaction_history</code>.
     */
    public final TransactionHistory TRANSACTION_HISTORY = TransactionHistory.TRANSACTION_HISTORY;

    /**
     * The table <code>money_transfer.transaction_status</code>.
     */
    public final TransactionStatus TRANSACTION_STATUS = TransactionStatus.TRANSACTION_STATUS;

    /**
     * The table <code>money_transfer.transaction_type</code>.
     */
    public final TransactionType TRANSACTION_TYPE = TransactionType.TRANSACTION_TYPE;

    /**
     * No further instances allowed
     */
    private MoneyTransfer() {
        super(DSL.name("money_transfer"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.MY_TABLE_ID_SEQ
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Account.ACCOUNT,
            TransactionHistory.TRANSACTION_HISTORY,
            TransactionStatus.TRANSACTION_STATUS,
            TransactionType.TRANSACTION_TYPE
        );
    }
}
