/*
 * This file is generated by jOOQ.
 */
package jooq.money_transfer;


import org.jooq.Sequence;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in money_transfer.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sequences {

    /**
     * The sequence <code>money_transfer.my_table_id_seq</code>
     */
    public static final Sequence<Long> MY_TABLE_ID_SEQ = Internal.createSequence("my_table_id_seq", MoneyTransfer.MONEY_TRANSFER, DSL.comment(""), SQLDataType.BIGINT.nullable(false), 100000, 100, null, null, false, null);
}
