/*
 * This file is generated by jOOQ.
 */
package jooq.money_transfer;


import jooq.money_transfer.tables.Account;
import jooq.money_transfer.tables.TransactionHistory;
import jooq.money_transfer.tables.TransactionStatus;
import jooq.money_transfer.tables.TransactionType;


/**
 * Convenience access to all tables in money_transfer.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>money_transfer.account</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>money_transfer.transaction_history</code>.
     */
    public static final TransactionHistory TRANSACTION_HISTORY = TransactionHistory.TRANSACTION_HISTORY;

    /**
     * The table <code>money_transfer.transaction_status</code>.
     */
    public static final TransactionStatus TRANSACTION_STATUS = TransactionStatus.TRANSACTION_STATUS;

    /**
     * The table <code>money_transfer.transaction_type</code>.
     */
    public static final TransactionType TRANSACTION_TYPE = TransactionType.TRANSACTION_TYPE;
}
